---
title: "FinalProject"
author: "Binh Ho"
date: "4/24/2022"
output: html_document
---

```{r}
library(ggplot2)
library(data.table)
library(tidyverse)
library(dplyr)

## Introduction

# Reading in all csv files as dataframes

equip_loss <- read.csv("russia_losses_equipment.csv")
exchange_rate <- read.csv("USD_RUB.csv")

## Explanation of how we altered data (weighted loss)

# Since equipment loss in the original dataset is cumulative, we calculated each value as a difference between it and the previous value, such that we could have equipment loss by day (not cumulative).

equip_loss = equip_loss %>%
  mutate(date = as.Date(date))
equip_loss$aircraft_per <- c(equip_loss$aircraft[1],diff(equip_loss$aircraft))
equip_loss$helicopter_per <- c(equip_loss$helicopter[1],diff(equip_loss$helicopter))
equip_loss$tank_per <- c(equip_loss$tank[1],diff(equip_loss$tank))
equip_loss$APC_per <- c(equip_loss$APC[1],diff(equip_loss$APC))
equip_loss$field_artillery_per <- c(equip_loss$field.artillery[1],diff(equip_loss$field.artillery))
equip_loss$MRL_per <- c(equip_loss$MRL[1],diff(equip_loss$MRL))
equip_loss$millitary_auto_per <- c(equip_loss$millitary.auto[1],diff(equip_loss$millitary.auto))
equip_loss$fuel_tank_per <- c(equip_loss$fuel.tank[1],diff(equip_loss$fuel.tank))
equip_loss$drone_per <- c(equip_loss$drone[1],diff(equip_loss$drone))
equip_loss$naval_ship_per <- c(equip_loss$naval.ship[1],diff(equip_loss$naval.ship))
equip_loss$anti_aircraft_warfare_per <- c(equip_loss$anti.aircraft.warfare[1],diff(equip_loss$anti.aircraft.warfare))
equip_loss$special_equipment_per <- c(equip_loss$special.equipment[1],diff(equip_loss$special.equipment))
equip_loss$mobile_SRBM_system_per <- c(equip_loss$mobile.SRBM.system[1],diff(equip_loss$mobile.SRBM.system))

# Calculated weighted loss based upon a formula that placed high value on losing expensive equipment

equip_loss$weighted_loss = c(equip_loss$tank*0.009 + equip_loss$aircraft*0.0716 + equip_loss$field_artillery_per*0.25 + equip_loss$helicopter*0.03444+equip_loss$naval_ship_per*0.6346)

# Makes modifications to exchange rate dataframe, converting the dates to a Date format, converting the change percentages to numbers rather than strings, and calculating real difference in exchange rate from day to day

exchange_rate = exchange_rate %>%
  mutate(Date = as.Date(Date, "%b %d %Y")) %>%
  mutate(Change = as.numeric(strsplit(Change.., "%"))) %>%
  mutate(date = Date, realchange = Price - Open)

head(equip_loss)
head(exchange_rate)

# We merge the two dataframes into one we will use for our analysis

full_frame <- full_join(equip_loss, exchange_rate, by = "date")
full_frame <- full_frame %>%
  filter(day < 51)
head(full_frame)
```
## Explanation of how we altered data (exchange rate)

```{r}

alt_real = c(full_frame$realchange[1], full_frame$realchange[2]) # Initializes a new vector that eventually will replace the realchange column. Since the resulting for loop involves examining the two prior values, which will not work for the first two values of the realchange column, these values are added in as the first two values of the vector.


for(i in 3:49){ # 3rd row until the end of the full_frame dataframe
  if((is.na(full_frame$realchange[i-2]))&(is.na(full_frame$realchange[i-1]))){ # Checks if the two previous days both have NA for realchange, i.e. the two previous days are weekends
    real_3 = full_frame$realchange[i] / 3 # Divides the change value for Monday by 3 to obtain an average of the change over Saturday, Sunday, and Monday
  } else{ # Day is not Monday
    real_3 = full_frame$realchange[i]
  }
  alt_real = c(alt_real, real_3) # Adds new value to the new realchange vector
}

# Running this for loop changes Sunday's NA values for exchange rate to the average calculated above

for(i in 1:49){ # Over all values in the alt_pct and alt_real vectors
  if(is.na(alt_real[i])){ # If day is Saturday or Sunday
    alt_real[i] = alt_real[i + 1] # Sunday value set to equal Monday value
  }
}

# Running the loop again changes Saturday's NA values for exchange rate to the average

for(i in 1:49){
  if(is.na(alt_real[i])){
    alt_real[i] = alt_real[i + 1] # Saturday value set to equal Sunday value
  }
}

full_frame <- mutate(full_frame, realchange = alt_real) # Changes realchange column to be alt_real vector, such that NA values on Saturday and Sunday are replaced with the average change value calculated based on Monday's value.

## Statement of what analysis we will conduct

model <- lm(realchange ~ weighted_loss, data = full_frame) # Regression with real_change as the Y and weighted_loss as the X
summary(model) # Prints necessary coefficients and p values

# Plot scatterplot of realchange vs. weighted loss, adding the regression line with coefficients generated by the model

ggplot(full_frame, aes(weighted_loss, realchange)) + 
  geom_point() +
  geom_abline(slope = model$coefficients[2],
              intercept = model$coefficients[1])

## Stating results and what they mean

```